// /* eslint-disable */
// // WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// const awsmobile = {
//     "aws_project_region": "us-east-2",
//     "aws_cognito_identity_pool_id": "us-east-2:f702be1e-bcc2-48eb-b571-242802c79f05",
//     "aws_cognito_region": "us-east-2",
//     "aws_user_pools_id": "us-east-2_QitC5KXk9",
//     "aws_user_pools_web_client_id": "179pllovmo8cek0a4gmrb4g9fg",
//     "oauth": {},
//     "aws_appsync_graphqlEndpoint": "https://ctxmi4oywjc3vfxuql6ciiuy7i.appsync-api.us-east-2.amazonaws.com/graphql",
//     "aws_appsync_region": "us-east-2",
//     "aws_appsync_authenticationType": "API_KEY",
//     "aws_appsync_apiKey": "da2-cguf3j2aange3ddomyx7m6zq6u"
// };


// export default awsmobile;
