// /* eslint-disable */
// // WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// const awsmobile = {
//     "aws_project_region": "us-east-2",
//     "aws_cognito_identity_pool_id": "us-east-2:f702be1e-bcc2-48eb-b571-242802c79f05",
//     "aws_cognito_region": "us-east-2",
//     "aws_user_pools_id": "us-east-2_QitC5KXk9",
//     "aws_user_pools_web_client_id": "179pllovmo8cek0a4gmrb4g9fg",
//     "oauth": {}
// };


// export default awsmobile;
